// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: relationship/relationship_service.proto

package relationship

import (
	common "chatnow-tests/proto/chatnow/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFriendsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Page      *common.PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListFriendsReq) Reset() {
	*x = ListFriendsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsReq) ProtoMessage() {}

func (x *ListFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsReq.ProtoReflect.Descriptor instead.
func (*ListFriendsReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListFriendsReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListFriendsReq) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListFriendsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	FriendList []*common.UserInfo     `protobuf:"bytes,2,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	Page       *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListFriendsRsp) Reset() {
	*x = ListFriendsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFriendsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRsp) ProtoMessage() {}

func (x *ListFriendsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRsp.ProtoReflect.Descriptor instead.
func (*ListFriendsRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFriendsRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListFriendsRsp) GetFriendList() []*common.UserInfo {
	if x != nil {
		return x.FriendList
	}
	return nil
}

func (x *ListFriendsRsp) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type SendFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RespondentId string `protobuf:"bytes,2,opt,name=respondent_id,json=respondentId,proto3" json:"respondent_id,omitempty"`
}

func (x *SendFriendReq) Reset() {
	*x = SendFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendReq) ProtoMessage() {}

func (x *SendFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendReq.ProtoReflect.Descriptor instead.
func (*SendFriendReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{2}
}

func (x *SendFriendReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendFriendReq) GetRespondentId() string {
	if x != nil {
		return x.RespondentId
	}
	return ""
}

type SendFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	NotifyEventId *string                `protobuf:"bytes,2,opt,name=notify_event_id,json=notifyEventId,proto3,oneof" json:"notify_event_id,omitempty"`
}

func (x *SendFriendRsp) Reset() {
	*x = SendFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRsp) ProtoMessage() {}

func (x *SendFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRsp.ProtoReflect.Descriptor instead.
func (*SendFriendRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{3}
}

func (x *SendFriendRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SendFriendRsp) GetNotifyEventId() string {
	if x != nil && x.NotifyEventId != nil {
		return *x.NotifyEventId
	}
	return ""
}

type HandleFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NotifyEventId string `protobuf:"bytes,2,opt,name=notify_event_id,json=notifyEventId,proto3" json:"notify_event_id,omitempty"`
	Agree         bool   `protobuf:"varint,3,opt,name=agree,proto3" json:"agree,omitempty"`
	ApplyUserId   string `protobuf:"bytes,4,opt,name=apply_user_id,json=applyUserId,proto3" json:"apply_user_id,omitempty"`
}

func (x *HandleFriendReq) Reset() {
	*x = HandleFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendReq) ProtoMessage() {}

func (x *HandleFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendReq.ProtoReflect.Descriptor instead.
func (*HandleFriendReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{4}
}

func (x *HandleFriendReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HandleFriendReq) GetNotifyEventId() string {
	if x != nil {
		return x.NotifyEventId
	}
	return ""
}

func (x *HandleFriendReq) GetAgree() bool {
	if x != nil {
		return x.Agree
	}
	return false
}

func (x *HandleFriendReq) GetApplyUserId() string {
	if x != nil {
		return x.ApplyUserId
	}
	return ""
}

type HandleFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header            *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	NewConversationId *string                `protobuf:"bytes,2,opt,name=new_conversation_id,json=newConversationId,proto3,oneof" json:"new_conversation_id,omitempty"`
}

func (x *HandleFriendRsp) Reset() {
	*x = HandleFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRsp) ProtoMessage() {}

func (x *HandleFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRsp.ProtoReflect.Descriptor instead.
func (*HandleFriendRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{5}
}

func (x *HandleFriendRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HandleFriendRsp) GetNewConversationId() string {
	if x != nil && x.NewConversationId != nil {
		return *x.NewConversationId
	}
	return ""
}

type RemoveFriendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PeerId    string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *RemoveFriendReq) Reset() {
	*x = RemoveFriendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFriendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendReq) ProtoMessage() {}

func (x *RemoveFriendReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendReq.ProtoReflect.Descriptor instead.
func (*RemoveFriendReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveFriendReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RemoveFriendReq) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type RemoveFriendRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RemoveFriendRsp) Reset() {
	*x = RemoveFriendRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFriendRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRsp) ProtoMessage() {}

func (x *RemoveFriendRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRsp.ProtoReflect.Descriptor instead.
func (*RemoveFriendRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveFriendRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type SearchFriendsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SearchKey string `protobuf:"bytes,2,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
}

func (x *SearchFriendsReq) Reset() {
	*x = SearchFriendsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFriendsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFriendsReq) ProtoMessage() {}

func (x *SearchFriendsReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFriendsReq.ProtoReflect.Descriptor instead.
func (*SearchFriendsReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{8}
}

func (x *SearchFriendsReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SearchFriendsReq) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

type SearchFriendsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	UserInfo []*common.UserInfo     `protobuf:"bytes,2,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
}

func (x *SearchFriendsRsp) Reset() {
	*x = SearchFriendsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFriendsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFriendsRsp) ProtoMessage() {}

func (x *SearchFriendsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFriendsRsp.ProtoReflect.Descriptor instead.
func (*SearchFriendsRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{9}
}

func (x *SearchFriendsRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SearchFriendsRsp) GetUserInfo() []*common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type BlockUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PeerId    string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *BlockUserReq) Reset() {
	*x = BlockUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserReq) ProtoMessage() {}

func (x *BlockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserReq.ProtoReflect.Descriptor instead.
func (*BlockUserReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{10}
}

func (x *BlockUserReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BlockUserReq) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type BlockUserRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *BlockUserRsp) Reset() {
	*x = BlockUserRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRsp) ProtoMessage() {}

func (x *BlockUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRsp.ProtoReflect.Descriptor instead.
func (*BlockUserRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{11}
}

func (x *BlockUserRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type UnblockUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PeerId    string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *UnblockUserReq) Reset() {
	*x = UnblockUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnblockUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserReq) ProtoMessage() {}

func (x *UnblockUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserReq.ProtoReflect.Descriptor instead.
func (*UnblockUserReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnblockUserReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnblockUserReq) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type UnblockUserRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *UnblockUserRsp) Reset() {
	*x = UnblockUserRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnblockUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserRsp) ProtoMessage() {}

func (x *UnblockUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserRsp.ProtoReflect.Descriptor instead.
func (*UnblockUserRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{13}
}

func (x *UnblockUserRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ListBlockedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Page      *common.PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListBlockedReq) Reset() {
	*x = ListBlockedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedReq) ProtoMessage() {}

func (x *ListBlockedReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedReq.ProtoReflect.Descriptor instead.
func (*ListBlockedReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListBlockedReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListBlockedReq) GetPage() *common.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListBlockedRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BlockedList []*common.UserInfo     `protobuf:"bytes,2,rep,name=blocked_list,json=blockedList,proto3" json:"blocked_list,omitempty"`
	Page        *common.PageResponse   `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListBlockedRsp) Reset() {
	*x = ListBlockedRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockedRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockedRsp) ProtoMessage() {}

func (x *ListBlockedRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockedRsp.ProtoReflect.Descriptor instead.
func (*ListBlockedRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListBlockedRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListBlockedRsp) GetBlockedList() []*common.UserInfo {
	if x != nil {
		return x.BlockedList
	}
	return nil
}

func (x *ListBlockedRsp) GetPage() *common.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListPendingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *ListPendingReq) Reset() {
	*x = ListPendingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPendingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingReq) ProtoMessage() {}

func (x *ListPendingReq) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingReq.ProtoReflect.Descriptor instead.
func (*ListPendingReq) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListPendingReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ListPendingRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Event  []*FriendEvent         `protobuf:"bytes,2,rep,name=event,proto3" json:"event,omitempty"`
}

func (x *ListPendingRsp) Reset() {
	*x = ListPendingRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPendingRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingRsp) ProtoMessage() {}

func (x *ListPendingRsp) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingRsp.ProtoReflect.Descriptor instead.
func (*ListPendingRsp) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListPendingRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ListPendingRsp) GetEvent() []*FriendEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type FriendEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string           `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Sender  *common.UserInfo `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *FriendEvent) Reset() {
	*x = FriendEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationship_relationship_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendEvent) ProtoMessage() {}

func (x *FriendEvent) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_relationship_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendEvent.ProtoReflect.Descriptor instead.
func (*FriendEvent) Descriptor() ([]byte, []int) {
	return file_relationship_relationship_service_proto_rawDescGZIP(), []int{18}
}

func (x *FriendEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FriendEvent) GetSender() *common.UserInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

var File_relationship_relationship_service_proto protoreflect.FileDescriptor

var file_relationship_relationship_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2f, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x68, 0x61, 0x74, 0x6e,
	0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x1a,
	0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0xb5, 0x01, 0x0a,
	0x0e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x22, 0x53, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0d, 0x53, 0x65,
	0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01,
	0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x67, 0x72, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x61, 0x67, 0x72, 0x65, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x13, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x11, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x6e,
	0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x22, 0x49, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x49, 0x0a,
	0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73, 0x70,
	0x12, 0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4b, 0x65, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x10, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x46,
	0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x48,
	0x0a, 0x0e, 0x55, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0e, 0x55, 0x6e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x22, 0x60, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f,
	0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x3b, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x2f,
	0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x22,
	0x81, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x73, 0x70, 0x12, 0x36, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x0b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x32,
	0xe6, 0x06, 0x0a, 0x13, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52,
	0x73, 0x70, 0x12, 0x5d, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f,
	0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x73,
	0x70, 0x12, 0x63, 0x0a, 0x13, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e,
	0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x25, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x73, 0x70, 0x12, 0x5c, 0x0a, 0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x25, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x52, 0x73, 0x70, 0x12, 0x5f, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x73, 0x12, 0x26, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x73, 0x52, 0x73, 0x70, 0x12, 0x53, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x22, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77,
	0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x59, 0x0a, 0x0b, 0x55, 0x6e,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x55, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x55, 0x6e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x73, 0x70, 0x12, 0x5e, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x52, 0x73, 0x70, 0x12, 0x61, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x24, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x68, 0x69, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x24, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x6e, 0x6f, 0x77, 0x2e, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x73, 0x70, 0x42, 0x03, 0x80, 0x01, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relationship_relationship_service_proto_rawDescOnce sync.Once
	file_relationship_relationship_service_proto_rawDescData = file_relationship_relationship_service_proto_rawDesc
)

func file_relationship_relationship_service_proto_rawDescGZIP() []byte {
	file_relationship_relationship_service_proto_rawDescOnce.Do(func() {
		file_relationship_relationship_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_relationship_relationship_service_proto_rawDescData)
	})
	return file_relationship_relationship_service_proto_rawDescData
}

var file_relationship_relationship_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_relationship_relationship_service_proto_goTypes = []any{
	(*ListFriendsReq)(nil),        // 0: chatnow.relationship.ListFriendsReq
	(*ListFriendsRsp)(nil),        // 1: chatnow.relationship.ListFriendsRsp
	(*SendFriendReq)(nil),         // 2: chatnow.relationship.SendFriendReq
	(*SendFriendRsp)(nil),         // 3: chatnow.relationship.SendFriendRsp
	(*HandleFriendReq)(nil),       // 4: chatnow.relationship.HandleFriendReq
	(*HandleFriendRsp)(nil),       // 5: chatnow.relationship.HandleFriendRsp
	(*RemoveFriendReq)(nil),       // 6: chatnow.relationship.RemoveFriendReq
	(*RemoveFriendRsp)(nil),       // 7: chatnow.relationship.RemoveFriendRsp
	(*SearchFriendsReq)(nil),      // 8: chatnow.relationship.SearchFriendsReq
	(*SearchFriendsRsp)(nil),      // 9: chatnow.relationship.SearchFriendsRsp
	(*BlockUserReq)(nil),          // 10: chatnow.relationship.BlockUserReq
	(*BlockUserRsp)(nil),          // 11: chatnow.relationship.BlockUserRsp
	(*UnblockUserReq)(nil),        // 12: chatnow.relationship.UnblockUserReq
	(*UnblockUserRsp)(nil),        // 13: chatnow.relationship.UnblockUserRsp
	(*ListBlockedReq)(nil),        // 14: chatnow.relationship.ListBlockedReq
	(*ListBlockedRsp)(nil),        // 15: chatnow.relationship.ListBlockedRsp
	(*ListPendingReq)(nil),        // 16: chatnow.relationship.ListPendingReq
	(*ListPendingRsp)(nil),        // 17: chatnow.relationship.ListPendingRsp
	(*FriendEvent)(nil),           // 18: chatnow.relationship.FriendEvent
	(*common.PageRequest)(nil),    // 19: chatnow.common.PageRequest
	(*common.ResponseHeader)(nil), // 20: chatnow.common.ResponseHeader
	(*common.UserInfo)(nil),       // 21: chatnow.common.UserInfo
	(*common.PageResponse)(nil),   // 22: chatnow.common.PageResponse
}
var file_relationship_relationship_service_proto_depIdxs = []int32{
	19, // 0: chatnow.relationship.ListFriendsReq.page:type_name -> chatnow.common.PageRequest
	20, // 1: chatnow.relationship.ListFriendsRsp.header:type_name -> chatnow.common.ResponseHeader
	21, // 2: chatnow.relationship.ListFriendsRsp.friend_list:type_name -> chatnow.common.UserInfo
	22, // 3: chatnow.relationship.ListFriendsRsp.page:type_name -> chatnow.common.PageResponse
	20, // 4: chatnow.relationship.SendFriendRsp.header:type_name -> chatnow.common.ResponseHeader
	20, // 5: chatnow.relationship.HandleFriendRsp.header:type_name -> chatnow.common.ResponseHeader
	20, // 6: chatnow.relationship.RemoveFriendRsp.header:type_name -> chatnow.common.ResponseHeader
	20, // 7: chatnow.relationship.SearchFriendsRsp.header:type_name -> chatnow.common.ResponseHeader
	21, // 8: chatnow.relationship.SearchFriendsRsp.user_info:type_name -> chatnow.common.UserInfo
	20, // 9: chatnow.relationship.BlockUserRsp.header:type_name -> chatnow.common.ResponseHeader
	20, // 10: chatnow.relationship.UnblockUserRsp.header:type_name -> chatnow.common.ResponseHeader
	19, // 11: chatnow.relationship.ListBlockedReq.page:type_name -> chatnow.common.PageRequest
	20, // 12: chatnow.relationship.ListBlockedRsp.header:type_name -> chatnow.common.ResponseHeader
	21, // 13: chatnow.relationship.ListBlockedRsp.blocked_list:type_name -> chatnow.common.UserInfo
	22, // 14: chatnow.relationship.ListBlockedRsp.page:type_name -> chatnow.common.PageResponse
	20, // 15: chatnow.relationship.ListPendingRsp.header:type_name -> chatnow.common.ResponseHeader
	18, // 16: chatnow.relationship.ListPendingRsp.event:type_name -> chatnow.relationship.FriendEvent
	21, // 17: chatnow.relationship.FriendEvent.sender:type_name -> chatnow.common.UserInfo
	0,  // 18: chatnow.relationship.RelationshipService.ListFriends:input_type -> chatnow.relationship.ListFriendsReq
	2,  // 19: chatnow.relationship.RelationshipService.SendFriendRequest:input_type -> chatnow.relationship.SendFriendReq
	4,  // 20: chatnow.relationship.RelationshipService.HandleFriendRequest:input_type -> chatnow.relationship.HandleFriendReq
	6,  // 21: chatnow.relationship.RelationshipService.RemoveFriend:input_type -> chatnow.relationship.RemoveFriendReq
	8,  // 22: chatnow.relationship.RelationshipService.SearchFriends:input_type -> chatnow.relationship.SearchFriendsReq
	10, // 23: chatnow.relationship.RelationshipService.BlockUser:input_type -> chatnow.relationship.BlockUserReq
	12, // 24: chatnow.relationship.RelationshipService.UnblockUser:input_type -> chatnow.relationship.UnblockUserReq
	14, // 25: chatnow.relationship.RelationshipService.ListBlockedUsers:input_type -> chatnow.relationship.ListBlockedReq
	16, // 26: chatnow.relationship.RelationshipService.ListPendingRequests:input_type -> chatnow.relationship.ListPendingReq
	1,  // 27: chatnow.relationship.RelationshipService.ListFriends:output_type -> chatnow.relationship.ListFriendsRsp
	3,  // 28: chatnow.relationship.RelationshipService.SendFriendRequest:output_type -> chatnow.relationship.SendFriendRsp
	5,  // 29: chatnow.relationship.RelationshipService.HandleFriendRequest:output_type -> chatnow.relationship.HandleFriendRsp
	7,  // 30: chatnow.relationship.RelationshipService.RemoveFriend:output_type -> chatnow.relationship.RemoveFriendRsp
	9,  // 31: chatnow.relationship.RelationshipService.SearchFriends:output_type -> chatnow.relationship.SearchFriendsRsp
	11, // 32: chatnow.relationship.RelationshipService.BlockUser:output_type -> chatnow.relationship.BlockUserRsp
	13, // 33: chatnow.relationship.RelationshipService.UnblockUser:output_type -> chatnow.relationship.UnblockUserRsp
	15, // 34: chatnow.relationship.RelationshipService.ListBlockedUsers:output_type -> chatnow.relationship.ListBlockedRsp
	17, // 35: chatnow.relationship.RelationshipService.ListPendingRequests:output_type -> chatnow.relationship.ListPendingRsp
	27, // [27:36] is the sub-list for method output_type
	18, // [18:27] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_relationship_relationship_service_proto_init() }
func file_relationship_relationship_service_proto_init() {
	if File_relationship_relationship_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_relationship_relationship_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListFriendsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListFriendsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SendFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SendFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*HandleFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*HandleFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveFriendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveFriendRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SearchFriendsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SearchFriendsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BlockUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*BlockUserRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*UnblockUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UnblockUserRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ListBlockedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ListBlockedRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ListPendingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ListPendingRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationship_relationship_service_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*FriendEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_relationship_relationship_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_relationship_relationship_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relationship_relationship_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relationship_relationship_service_proto_goTypes,
		DependencyIndexes: file_relationship_relationship_service_proto_depIdxs,
		MessageInfos:      file_relationship_relationship_service_proto_msgTypes,
	}.Build()
	File_relationship_relationship_service_proto = out.File
	file_relationship_relationship_service_proto_rawDesc = nil
	file_relationship_relationship_service_proto_goTypes = nil
	file_relationship_relationship_service_proto_depIdxs = nil
}
