-run_mode=true
-log_file=/im/logs/message.log
-log_level=0
-registry_host=http://10.0.4.10:2379
-base_service=/service
-instance_name=/message_service/instance
-access_host=10.0.4.10:10005
-listen_port=10005
-rpc_timeout=-1
-rpc_threads=1
-identity_service=/service/identity_service
-media_service=/service/media_service
-mysql_host=10.0.4.10
-mysql_user=root
-mysql_pswd=YHY060403
-mysql_db=chatnow
-mysql_cset=utf8
-mysql_port=0
-mysql_pool_count=4
-mq_user=root
-mq_pswd=YHY060403
-mq_host=10.0.4.10:5672
-mq_msg_exchange=chat_msg_exchange
-mq_msg_queue_db=msg_queue_db
-mq_msg_queue_es=msg_queue_es
-mq_db_binding_key=msg_db
-mq_es_binding_key=msg_es
-mq_push_exchange=chat_push_exchange
-mq_push_queue=msg_push_queue
-mq_push_binding_key=push
-mq_es_exchange=es_index_exchange
-mq_es_queue=msg_queue_es_index
-mq_es_binding_key=msg_queue_es_index
-es_host=http://10.0.4.10:9200/
-redis_host=10.0.4.10
-redis_port=6379
-redis_db=0
-redis_keep_alive=true
-redis_pool_size=8