# Presence 服务配置
-run_mode=false
-log_file=presence_server.log
-log_level=0

# RPC 端口
-listen_port=9050

# 注册中心
-registry_host=http://127.0.0.1:2379
-base_service=/service
-push_service=/service/push_service

# Redis
-redis_host=127.0.0.1
-redis_port=6379
-redis_db=0
-redis_keep_alive=true

# 状态扫描间隔（秒）
-change_scan_interval_sec=5
