/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */
USE chatnow;

DROP TABLE IF EXISTS `user_timeline`;

CREATE TABLE `user_timeline` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(64) NOT NULL,
  `session_id` varchar(64) NOT NULL,
  `message_id` bigint NOT NULL,
  `message_time` TIMESTAMP NULL)
 ENGINE=InnoDB;

CREATE INDEX `idx_user_msg`
  ON `user_timeline` (
    `user_id`,
    `message_id`);

CREATE INDEX `idx_user_session_msg`
  ON `user_timeline` (
    `user_id`,
    `session_id`,
    `message_id`);

