-run_mode=true
-log_file=/home/icepop/ChatNow/logs/identity.log
-log_level=0
-registry_host=http://127.0.0.1:2379
-base_service=/service
-instance_name=/identity_service/instance
-access_host=127.0.0.1:10003
-listen_port=10003
-rpc_timeout=-1
-rpc_threads=1
-media_public_url_prefix=https://cdn.chatnow.com/public
-es_host=http://127.0.0.1:9200/
-mysql_host=127.0.0.1
-mysql_user=root
-mysql_pswd=YHY060403
-mysql_db=chatnow
-mysql_cset=utf8
-mysql_port=0
-mysql_pool_count=4
-redis_host=127.0.0.1
-redis_port=6379
-redis_db=0
-redis_seeds=127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384
-redis_keep_alive=true
-mail_user=yhaoyang666@163.com
-mail_paswd=XKk5zvYwWKeB8xNk
-mail_host=smtps://smtp.163.com:465
-mail_from=yhaoyang666@163.com
-auth_config=/home/icepop/ChatNow/conf/auth.json