-run_mode=true
-log_file=/im/logs/identity.log
-log_level=0
-registry_host=http://etcd:2379
-base_service=/service
-instance_name=/identity_service/instance
-access_host=identity_server:10003
-listen_port=10003
-rpc_timeout=-1
-rpc_threads=1
-media_public_url_prefix=https://cdn.chatnow.com/public
-es_host=http://elasticsearch:9200/
-mysql_host=mysql
-mysql_user=root
-mysql_db=chatnow
-mysql_cset=utf8
-mysql_port=0
-mysql_pool_count=4
-redis_host=redis-node1
-redis_port=6379
-redis_db=0
-redis_seeds=redis-node1:6379,redis-node2:6380,redis-node3:6381,redis-node4:6382,redis-node5:6383,redis-node6:6384
-redis_keep_alive=true
-mail_user=yhaoyang666@163.com
-mail_host=smtps://smtp.163.com:465
-mail_from=yhaoyang666@163.com
