# Presence 服务配置
-run_mode=false
-log_file=/im/logs/presence.log
-log_level=0

# RPC 端口
-listen_port=9050

# 注册中心
-registry_host=http://etcd:2379
-base_service=/service
-instance_name=/presence_service/instance
-access_host=presence_server:9050
-push_service=/service/push_service

# Redis
-redis_host=redis-node1
-redis_port=6379
-redis_db=0
-redis_seeds=redis-node1:6379,redis-node2:6380,redis-node3:6381,redis-node4:6382,redis-node5:6383,redis-node6:6384
-redis_keep_alive=true

# 状态扫描间隔（秒）
-change_scan_interval_sec=5
