// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: push/notify.proto

package push

import (
	common "chatnow-tests/proto/chatnow/common"
	message "chatnow-tests/proto/chatnow/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyType int32

const (
	NotifyType_FRIEND_ADD_APPLY_NOTIFY       NotifyType = 0
	NotifyType_FRIEND_ADD_PROCESS_NOTIFY     NotifyType = 1
	NotifyType_CONVERSATION_CREATE_NOTIFY    NotifyType = 2
	NotifyType_CHAT_MESSAGE_NOTIFY           NotifyType = 3
	NotifyType_FRIEND_REMOVE_NOTIFY          NotifyType = 4
	NotifyType_MESSAGE_RECALLED_NOTIFY       NotifyType = 5
	NotifyType_PRESENCE_CHANGE_NOTIFY        NotifyType = 6
	NotifyType_TYPING_NOTIFY                 NotifyType = 7
	NotifyType_REACTION_CHANGED_NOTIFY       NotifyType = 8
	NotifyType_PIN_CHANGED_NOTIFY            NotifyType = 9
	NotifyType_READ_RECEIPT_NOTIFY           NotifyType = 10
	NotifyType_KICKED_BY_NEW_DEVICE          NotifyType = 11
	NotifyType_KICKED_BY_REVOKE              NotifyType = 12
	NotifyType_FORCE_LOGOUT                  NotifyType = 13
	NotifyType_CONVERSATION_DISMISSED_NOTIFY NotifyType = 14
	NotifyType_CLIENT_AUTH                   NotifyType = 49
	NotifyType_MSG_PUSH_ACK                  NotifyType = 50
	NotifyType_CLIENT_HEARTBEAT              NotifyType = 51
)

// Enum value maps for NotifyType.
var (
	NotifyType_name = map[int32]string{
		0:  "FRIEND_ADD_APPLY_NOTIFY",
		1:  "FRIEND_ADD_PROCESS_NOTIFY",
		2:  "CONVERSATION_CREATE_NOTIFY",
		3:  "CHAT_MESSAGE_NOTIFY",
		4:  "FRIEND_REMOVE_NOTIFY",
		5:  "MESSAGE_RECALLED_NOTIFY",
		6:  "PRESENCE_CHANGE_NOTIFY",
		7:  "TYPING_NOTIFY",
		8:  "REACTION_CHANGED_NOTIFY",
		9:  "PIN_CHANGED_NOTIFY",
		10: "READ_RECEIPT_NOTIFY",
		11: "KICKED_BY_NEW_DEVICE",
		12: "KICKED_BY_REVOKE",
		13: "FORCE_LOGOUT",
		14: "CONVERSATION_DISMISSED_NOTIFY",
		49: "CLIENT_AUTH",
		50: "MSG_PUSH_ACK",
		51: "CLIENT_HEARTBEAT",
	}
	NotifyType_value = map[string]int32{
		"FRIEND_ADD_APPLY_NOTIFY":       0,
		"FRIEND_ADD_PROCESS_NOTIFY":     1,
		"CONVERSATION_CREATE_NOTIFY":    2,
		"CHAT_MESSAGE_NOTIFY":           3,
		"FRIEND_REMOVE_NOTIFY":          4,
		"MESSAGE_RECALLED_NOTIFY":       5,
		"PRESENCE_CHANGE_NOTIFY":        6,
		"TYPING_NOTIFY":                 7,
		"REACTION_CHANGED_NOTIFY":       8,
		"PIN_CHANGED_NOTIFY":            9,
		"READ_RECEIPT_NOTIFY":           10,
		"KICKED_BY_NEW_DEVICE":          11,
		"KICKED_BY_REVOKE":              12,
		"FORCE_LOGOUT":                  13,
		"CONVERSATION_DISMISSED_NOTIFY": 14,
		"CLIENT_AUTH":                   49,
		"MSG_PUSH_ACK":                  50,
		"CLIENT_HEARTBEAT":              51,
	}
)

func (x NotifyType) Enum() *NotifyType {
	p := new(NotifyType)
	*p = x
	return p
}

func (x NotifyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyType) Descriptor() protoreflect.EnumDescriptor {
	return file_push_notify_proto_enumTypes[0].Descriptor()
}

func (NotifyType) Type() protoreflect.EnumType {
	return &file_push_notify_proto_enumTypes[0]
}

func (x NotifyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyType.Descriptor instead.
func (NotifyType) EnumDescriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{0}
}

type NotifyClientAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastUserSeq   *uint64                `protobuf:"varint,3,opt,name=last_user_seq,json=lastUserSeq,proto3,oneof" json:"last_user_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyClientAuth) Reset() {
	*x = NotifyClientAuth{}
	mi := &file_push_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyClientAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyClientAuth) ProtoMessage() {}

func (x *NotifyClientAuth) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyClientAuth.ProtoReflect.Descriptor instead.
func (*NotifyClientAuth) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyClientAuth) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *NotifyClientAuth) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NotifyClientAuth) GetLastUserSeq() uint64 {
	if x != nil && x.LastUserSeq != nil {
		return *x.LastUserSeq
	}
	return 0
}

type NotifyMsgPushAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId       string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	MessageId      int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserSeq        uint64                 `protobuf:"varint,4,opt,name=user_seq,json=userSeq,proto3" json:"user_seq,omitempty"`
	ConversationId string                 `protobuf:"bytes,5,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyMsgPushAck) Reset() {
	*x = NotifyMsgPushAck{}
	mi := &file_push_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMsgPushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMsgPushAck) ProtoMessage() {}

func (x *NotifyMsgPushAck) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMsgPushAck.ProtoReflect.Descriptor instead.
func (*NotifyMsgPushAck) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyMsgPushAck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyMsgPushAck) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *NotifyMsgPushAck) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NotifyMsgPushAck) GetUserSeq() uint64 {
	if x != nil {
		return x.UserSeq
	}
	return 0
}

func (x *NotifyMsgPushAck) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type NotifyHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastUserSeq   uint64                 `protobuf:"varint,2,opt,name=last_user_seq,json=lastUserSeq,proto3" json:"last_user_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyHeartbeat) Reset() {
	*x = NotifyHeartbeat{}
	mi := &file_push_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyHeartbeat) ProtoMessage() {}

func (x *NotifyHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyHeartbeat.ProtoReflect.Descriptor instead.
func (*NotifyHeartbeat) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyHeartbeat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyHeartbeat) GetLastUserSeq() uint64 {
	if x != nil {
		return x.LastUserSeq
	}
	return 0
}

type NotifyFriendAddApply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFriendAddApply) Reset() {
	*x = NotifyFriendAddApply{}
	mi := &file_push_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFriendAddApply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFriendAddApply) ProtoMessage() {}

func (x *NotifyFriendAddApply) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFriendAddApply.ProtoReflect.Descriptor instead.
func (*NotifyFriendAddApply) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{3}
}

func (x *NotifyFriendAddApply) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type NotifyFriendAddProcess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agree         bool                   `protobuf:"varint,1,opt,name=agree,proto3" json:"agree,omitempty"`
	UserInfo      *common.UserInfo       `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFriendAddProcess) Reset() {
	*x = NotifyFriendAddProcess{}
	mi := &file_push_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFriendAddProcess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFriendAddProcess) ProtoMessage() {}

func (x *NotifyFriendAddProcess) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFriendAddProcess.ProtoReflect.Descriptor instead.
func (*NotifyFriendAddProcess) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyFriendAddProcess) GetAgree() bool {
	if x != nil {
		return x.Agree
	}
	return false
}

func (x *NotifyFriendAddProcess) GetUserInfo() *common.UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type NotifyFriendRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFriendRemove) Reset() {
	*x = NotifyFriendRemove{}
	mi := &file_push_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFriendRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFriendRemove) ProtoMessage() {}

func (x *NotifyFriendRemove) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFriendRemove.ProtoReflect.Descriptor instead.
func (*NotifyFriendRemove) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyFriendRemove) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotifyNewConversation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConversationPayload []byte                 `protobuf:"bytes,1,opt,name=conversation_payload,json=conversationPayload,proto3" json:"conversation_payload,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *NotifyNewConversation) Reset() {
	*x = NotifyNewConversation{}
	mi := &file_push_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewConversation) ProtoMessage() {}

func (x *NotifyNewConversation) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewConversation.ProtoReflect.Descriptor instead.
func (*NotifyNewConversation) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyNewConversation) GetConversationPayload() []byte {
	if x != nil {
		return x.ConversationPayload
	}
	return nil
}

type NotifyNewMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageInfo   *message.Message       `protobuf:"bytes,1,opt,name=message_info,json=messageInfo,proto3" json:"message_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewMessage) Reset() {
	*x = NotifyNewMessage{}
	mi := &file_push_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewMessage) ProtoMessage() {}

func (x *NotifyNewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewMessage.ProtoReflect.Descriptor instead.
func (*NotifyNewMessage) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyNewMessage) GetMessageInfo() *message.Message {
	if x != nil {
		return x.MessageInfo
	}
	return nil
}

type NotifyMessageRecalled struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyMessageRecalled) Reset() {
	*x = NotifyMessageRecalled{}
	mi := &file_push_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMessageRecalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMessageRecalled) ProtoMessage() {}

func (x *NotifyMessageRecalled) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMessageRecalled.ProtoReflect.Descriptor instead.
func (*NotifyMessageRecalled) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyMessageRecalled) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NotifyMessageRecalled) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type NotifyPresenceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPresenceChange) Reset() {
	*x = NotifyPresenceChange{}
	mi := &file_push_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPresenceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPresenceChange) ProtoMessage() {}

func (x *NotifyPresenceChange) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPresenceChange.ProtoReflect.Descriptor instead.
func (*NotifyPresenceChange) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyPresenceChange) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyPresenceChange) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type NotifyTyping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	IsTyping       bool                   `protobuf:"varint,3,opt,name=is_typing,json=isTyping,proto3" json:"is_typing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyTyping) Reset() {
	*x = NotifyTyping{}
	mi := &file_push_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTyping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTyping) ProtoMessage() {}

func (x *NotifyTyping) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTyping.ProtoReflect.Descriptor instead.
func (*NotifyTyping) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyTyping) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotifyTyping) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NotifyTyping) GetIsTyping() bool {
	if x != nil {
		return x.IsTyping
	}
	return false
}

type NotifyReactionChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Emoji          string                 `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Added          bool                   `protobuf:"varint,5,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyReactionChanged) Reset() {
	*x = NotifyReactionChanged{}
	mi := &file_push_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReactionChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReactionChanged) ProtoMessage() {}

func (x *NotifyReactionChanged) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReactionChanged.ProtoReflect.Descriptor instead.
func (*NotifyReactionChanged) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyReactionChanged) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NotifyReactionChanged) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NotifyReactionChanged) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *NotifyReactionChanged) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *NotifyReactionChanged) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type NotifyPinChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId      int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ActorUserId    string                 `protobuf:"bytes,3,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	IsPinned       bool                   `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyPinChanged) Reset() {
	*x = NotifyPinChanged{}
	mi := &file_push_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPinChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPinChanged) ProtoMessage() {}

func (x *NotifyPinChanged) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPinChanged.ProtoReflect.Descriptor instead.
func (*NotifyPinChanged) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyPinChanged) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NotifyPinChanged) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *NotifyPinChanged) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *NotifyPinChanged) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type NotifyReadReceipt struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReaderUserId   string                 `protobuf:"bytes,2,opt,name=reader_user_id,json=readerUserId,proto3" json:"reader_user_id,omitempty"`
	LastReadSeq    uint64                 `protobuf:"varint,3,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyReadReceipt) Reset() {
	*x = NotifyReadReceipt{}
	mi := &file_push_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyReadReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReadReceipt) ProtoMessage() {}

func (x *NotifyReadReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReadReceipt.ProtoReflect.Descriptor instead.
func (*NotifyReadReceipt) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyReadReceipt) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *NotifyReadReceipt) GetReaderUserId() string {
	if x != nil {
		return x.ReaderUserId
	}
	return ""
}

func (x *NotifyReadReceipt) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

type NotifyKicked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        NotifyType             `protobuf:"varint,1,opt,name=reason,proto3,enum=chatnow.push.NotifyType" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyKicked) Reset() {
	*x = NotifyKicked{}
	mi := &file_push_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyKicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyKicked) ProtoMessage() {}

func (x *NotifyKicked) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyKicked.ProtoReflect.Descriptor instead.
func (*NotifyKicked) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyKicked) GetReason() NotifyType {
	if x != nil {
		return x.Reason
	}
	return NotifyType_FRIEND_ADD_APPLY_NOTIFY
}

func (x *NotifyKicked) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotifyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyEventId *string                `protobuf:"bytes,1,opt,name=notify_event_id,json=notifyEventId,proto3,oneof" json:"notify_event_id,omitempty"`
	NotifyType    NotifyType             `protobuf:"varint,2,opt,name=notify_type,json=notifyType,proto3,enum=chatnow.push.NotifyType" json:"notify_type,omitempty"`
	TraceId       *string                `protobuf:"bytes,14,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	// Types that are valid to be assigned to NotifyRemarks:
	//
	//	*NotifyMessage_FriendAddApply
	//	*NotifyMessage_FriendProcessResult
	//	*NotifyMessage_FriendRemove
	//	*NotifyMessage_NewConversationInfo
	//	*NotifyMessage_NewMessageInfo
	//	*NotifyMessage_MsgPushAck
	//	*NotifyMessage_Heartbeat
	//	*NotifyMessage_ClientAuth
	//	*NotifyMessage_MessageRecalled
	//	*NotifyMessage_PresenceChange
	//	*NotifyMessage_Typing
	//	*NotifyMessage_ReactionChanged
	//	*NotifyMessage_PinChanged
	//	*NotifyMessage_ReadReceipt
	//	*NotifyMessage_Kicked
	NotifyRemarks isNotifyMessage_NotifyRemarks `protobuf_oneof:"notify_remarks"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMessage) Reset() {
	*x = NotifyMessage{}
	mi := &file_push_notify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMessage) ProtoMessage() {}

func (x *NotifyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_push_notify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMessage.ProtoReflect.Descriptor instead.
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return file_push_notify_proto_rawDescGZIP(), []int{15}
}

func (x *NotifyMessage) GetNotifyEventId() string {
	if x != nil && x.NotifyEventId != nil {
		return *x.NotifyEventId
	}
	return ""
}

func (x *NotifyMessage) GetNotifyType() NotifyType {
	if x != nil {
		return x.NotifyType
	}
	return NotifyType_FRIEND_ADD_APPLY_NOTIFY
}

func (x *NotifyMessage) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *NotifyMessage) GetNotifyRemarks() isNotifyMessage_NotifyRemarks {
	if x != nil {
		return x.NotifyRemarks
	}
	return nil
}

func (x *NotifyMessage) GetFriendAddApply() *NotifyFriendAddApply {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_FriendAddApply); ok {
			return x.FriendAddApply
		}
	}
	return nil
}

func (x *NotifyMessage) GetFriendProcessResult() *NotifyFriendAddProcess {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_FriendProcessResult); ok {
			return x.FriendProcessResult
		}
	}
	return nil
}

func (x *NotifyMessage) GetFriendRemove() *NotifyFriendRemove {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_FriendRemove); ok {
			return x.FriendRemove
		}
	}
	return nil
}

func (x *NotifyMessage) GetNewConversationInfo() *NotifyNewConversation {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_NewConversationInfo); ok {
			return x.NewConversationInfo
		}
	}
	return nil
}

func (x *NotifyMessage) GetNewMessageInfo() *NotifyNewMessage {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_NewMessageInfo); ok {
			return x.NewMessageInfo
		}
	}
	return nil
}

func (x *NotifyMessage) GetMsgPushAck() *NotifyMsgPushAck {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_MsgPushAck); ok {
			return x.MsgPushAck
		}
	}
	return nil
}

func (x *NotifyMessage) GetHeartbeat() *NotifyHeartbeat {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *NotifyMessage) GetClientAuth() *NotifyClientAuth {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_ClientAuth); ok {
			return x.ClientAuth
		}
	}
	return nil
}

func (x *NotifyMessage) GetMessageRecalled() *NotifyMessageRecalled {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_MessageRecalled); ok {
			return x.MessageRecalled
		}
	}
	return nil
}

func (x *NotifyMessage) GetPresenceChange() *NotifyPresenceChange {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_PresenceChange); ok {
			return x.PresenceChange
		}
	}
	return nil
}

func (x *NotifyMessage) GetTyping() *NotifyTyping {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_Typing); ok {
			return x.Typing
		}
	}
	return nil
}

func (x *NotifyMessage) GetReactionChanged() *NotifyReactionChanged {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_ReactionChanged); ok {
			return x.ReactionChanged
		}
	}
	return nil
}

func (x *NotifyMessage) GetPinChanged() *NotifyPinChanged {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_PinChanged); ok {
			return x.PinChanged
		}
	}
	return nil
}

func (x *NotifyMessage) GetReadReceipt() *NotifyReadReceipt {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_ReadReceipt); ok {
			return x.ReadReceipt
		}
	}
	return nil
}

func (x *NotifyMessage) GetKicked() *NotifyKicked {
	if x != nil {
		if x, ok := x.NotifyRemarks.(*NotifyMessage_Kicked); ok {
			return x.Kicked
		}
	}
	return nil
}

type isNotifyMessage_NotifyRemarks interface {
	isNotifyMessage_NotifyRemarks()
}

type NotifyMessage_FriendAddApply struct {
	FriendAddApply *NotifyFriendAddApply `protobuf:"bytes,3,opt,name=friend_add_apply,json=friendAddApply,proto3,oneof"`
}

type NotifyMessage_FriendProcessResult struct {
	FriendProcessResult *NotifyFriendAddProcess `protobuf:"bytes,4,opt,name=friend_process_result,json=friendProcessResult,proto3,oneof"`
}

type NotifyMessage_FriendRemove struct {
	FriendRemove *NotifyFriendRemove `protobuf:"bytes,7,opt,name=friend_remove,json=friendRemove,proto3,oneof"`
}

type NotifyMessage_NewConversationInfo struct {
	NewConversationInfo *NotifyNewConversation `protobuf:"bytes,5,opt,name=new_conversation_info,json=newConversationInfo,proto3,oneof"`
}

type NotifyMessage_NewMessageInfo struct {
	NewMessageInfo *NotifyNewMessage `protobuf:"bytes,6,opt,name=new_message_info,json=newMessageInfo,proto3,oneof"`
}

type NotifyMessage_MsgPushAck struct {
	MsgPushAck *NotifyMsgPushAck `protobuf:"bytes,8,opt,name=msg_push_ack,json=msgPushAck,proto3,oneof"`
}

type NotifyMessage_Heartbeat struct {
	Heartbeat *NotifyHeartbeat `protobuf:"bytes,9,opt,name=heartbeat,proto3,oneof"`
}

type NotifyMessage_ClientAuth struct {
	ClientAuth *NotifyClientAuth `protobuf:"bytes,10,opt,name=client_auth,json=clientAuth,proto3,oneof"`
}

type NotifyMessage_MessageRecalled struct {
	MessageRecalled *NotifyMessageRecalled `protobuf:"bytes,11,opt,name=message_recalled,json=messageRecalled,proto3,oneof"`
}

type NotifyMessage_PresenceChange struct {
	PresenceChange *NotifyPresenceChange `protobuf:"bytes,12,opt,name=presence_change,json=presenceChange,proto3,oneof"`
}

type NotifyMessage_Typing struct {
	Typing *NotifyTyping `protobuf:"bytes,13,opt,name=typing,proto3,oneof"`
}

type NotifyMessage_ReactionChanged struct {
	ReactionChanged *NotifyReactionChanged `protobuf:"bytes,15,opt,name=reaction_changed,json=reactionChanged,proto3,oneof"`
}

type NotifyMessage_PinChanged struct {
	PinChanged *NotifyPinChanged `protobuf:"bytes,16,opt,name=pin_changed,json=pinChanged,proto3,oneof"`
}

type NotifyMessage_ReadReceipt struct {
	ReadReceipt *NotifyReadReceipt `protobuf:"bytes,17,opt,name=read_receipt,json=readReceipt,proto3,oneof"`
}

type NotifyMessage_Kicked struct {
	Kicked *NotifyKicked `protobuf:"bytes,18,opt,name=kicked,proto3,oneof"`
}

func (*NotifyMessage_FriendAddApply) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_FriendProcessResult) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_FriendRemove) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_NewConversationInfo) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_NewMessageInfo) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_MsgPushAck) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_Heartbeat) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_ClientAuth) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_MessageRecalled) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_PresenceChange) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_Typing) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_ReactionChanged) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_PinChanged) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_ReadReceipt) isNotifyMessage_NotifyRemarks() {}

func (*NotifyMessage_Kicked) isNotifyMessage_NotifyRemarks() {}

var File_push_notify_proto protoreflect.FileDescriptor

const file_push_notify_proto_rawDesc = "" +
	"\n" +
	"\x11push/notify.proto\x12\fchatnow.push\x1a\x12common/types.proto\x1a\x1bmessage/message_types.proto\"\x8d\x01\n" +
	"\x10NotifyClientAuth\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12'\n" +
	"\rlast_user_seq\x18\x03 \x01(\x04H\x00R\vlastUserSeq\x88\x01\x01B\x10\n" +
	"\x0e_last_user_seq\"\xab\x01\n" +
	"\x10NotifyMsgPushAck\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x19\n" +
	"\buser_seq\x18\x04 \x01(\x04R\auserSeq\x12'\n" +
	"\x0fconversation_id\x18\x05 \x01(\tR\x0econversationId\"N\n" +
	"\x0fNotifyHeartbeat\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\rlast_user_seq\x18\x02 \x01(\x04R\vlastUserSeq\"M\n" +
	"\x14NotifyFriendAddApply\x125\n" +
	"\tuser_info\x18\x01 \x01(\v2\x18.chatnow.common.UserInfoR\buserInfo\"e\n" +
	"\x16NotifyFriendAddProcess\x12\x14\n" +
	"\x05agree\x18\x01 \x01(\bR\x05agree\x125\n" +
	"\tuser_info\x18\x02 \x01(\v2\x18.chatnow.common.UserInfoR\buserInfo\"-\n" +
	"\x12NotifyFriendRemove\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"J\n" +
	"\x15NotifyNewConversation\x121\n" +
	"\x14conversation_payload\x18\x01 \x01(\fR\x13conversationPayload\"O\n" +
	"\x10NotifyNewMessage\x12;\n" +
	"\fmessage_info\x18\x01 \x01(\v2\x18.chatnow.message.MessageR\vmessageInfo\"_\n" +
	"\x15NotifyMessageRecalled\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"E\n" +
	"\x14NotifyPresenceChange\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"m\n" +
	"\fNotifyTyping\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tis_typing\x18\x03 \x01(\bR\bisTyping\"\xaf\x01\n" +
	"\x15NotifyReactionChanged\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emoji\x12\x14\n" +
	"\x05added\x18\x05 \x01(\bR\x05added\"\x9b\x01\n" +
	"\x10NotifyPinChanged\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\"\n" +
	"\ractor_user_id\x18\x03 \x01(\tR\vactorUserId\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\bR\bisPinned\"\x86\x01\n" +
	"\x11NotifyReadReceipt\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12$\n" +
	"\x0ereader_user_id\x18\x02 \x01(\tR\freaderUserId\x12\"\n" +
	"\rlast_read_seq\x18\x03 \x01(\x04R\vlastReadSeq\"Z\n" +
	"\fNotifyKicked\x120\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x18.chatnow.push.NotifyTypeR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\n" +
	"\n" +
	"\rNotifyMessage\x12+\n" +
	"\x0fnotify_event_id\x18\x01 \x01(\tH\x01R\rnotifyEventId\x88\x01\x01\x129\n" +
	"\vnotify_type\x18\x02 \x01(\x0e2\x18.chatnow.push.NotifyTypeR\n" +
	"notifyType\x12\x1e\n" +
	"\btrace_id\x18\x0e \x01(\tH\x02R\atraceId\x88\x01\x01\x12N\n" +
	"\x10friend_add_apply\x18\x03 \x01(\v2\".chatnow.push.NotifyFriendAddApplyH\x00R\x0efriendAddApply\x12Z\n" +
	"\x15friend_process_result\x18\x04 \x01(\v2$.chatnow.push.NotifyFriendAddProcessH\x00R\x13friendProcessResult\x12G\n" +
	"\rfriend_remove\x18\a \x01(\v2 .chatnow.push.NotifyFriendRemoveH\x00R\ffriendRemove\x12Y\n" +
	"\x15new_conversation_info\x18\x05 \x01(\v2#.chatnow.push.NotifyNewConversationH\x00R\x13newConversationInfo\x12J\n" +
	"\x10new_message_info\x18\x06 \x01(\v2\x1e.chatnow.push.NotifyNewMessageH\x00R\x0enewMessageInfo\x12B\n" +
	"\fmsg_push_ack\x18\b \x01(\v2\x1e.chatnow.push.NotifyMsgPushAckH\x00R\n" +
	"msgPushAck\x12=\n" +
	"\theartbeat\x18\t \x01(\v2\x1d.chatnow.push.NotifyHeartbeatH\x00R\theartbeat\x12A\n" +
	"\vclient_auth\x18\n" +
	" \x01(\v2\x1e.chatnow.push.NotifyClientAuthH\x00R\n" +
	"clientAuth\x12P\n" +
	"\x10message_recalled\x18\v \x01(\v2#.chatnow.push.NotifyMessageRecalledH\x00R\x0fmessageRecalled\x12M\n" +
	"\x0fpresence_change\x18\f \x01(\v2\".chatnow.push.NotifyPresenceChangeH\x00R\x0epresenceChange\x124\n" +
	"\x06typing\x18\r \x01(\v2\x1a.chatnow.push.NotifyTypingH\x00R\x06typing\x12P\n" +
	"\x10reaction_changed\x18\x0f \x01(\v2#.chatnow.push.NotifyReactionChangedH\x00R\x0freactionChanged\x12A\n" +
	"\vpin_changed\x18\x10 \x01(\v2\x1e.chatnow.push.NotifyPinChangedH\x00R\n" +
	"pinChanged\x12D\n" +
	"\fread_receipt\x18\x11 \x01(\v2\x1f.chatnow.push.NotifyReadReceiptH\x00R\vreadReceipt\x124\n" +
	"\x06kicked\x18\x12 \x01(\v2\x1a.chatnow.push.NotifyKickedH\x00R\x06kickedB\x10\n" +
	"\x0enotify_remarksB\x12\n" +
	"\x10_notify_event_idB\v\n" +
	"\t_trace_id*\xd3\x03\n" +
	"\n" +
	"NotifyType\x12\x1b\n" +
	"\x17FRIEND_ADD_APPLY_NOTIFY\x10\x00\x12\x1d\n" +
	"\x19FRIEND_ADD_PROCESS_NOTIFY\x10\x01\x12\x1e\n" +
	"\x1aCONVERSATION_CREATE_NOTIFY\x10\x02\x12\x17\n" +
	"\x13CHAT_MESSAGE_NOTIFY\x10\x03\x12\x18\n" +
	"\x14FRIEND_REMOVE_NOTIFY\x10\x04\x12\x1b\n" +
	"\x17MESSAGE_RECALLED_NOTIFY\x10\x05\x12\x1a\n" +
	"\x16PRESENCE_CHANGE_NOTIFY\x10\x06\x12\x11\n" +
	"\rTYPING_NOTIFY\x10\a\x12\x1b\n" +
	"\x17REACTION_CHANGED_NOTIFY\x10\b\x12\x16\n" +
	"\x12PIN_CHANGED_NOTIFY\x10\t\x12\x17\n" +
	"\x13READ_RECEIPT_NOTIFY\x10\n" +
	"\x12\x18\n" +
	"\x14KICKED_BY_NEW_DEVICE\x10\v\x12\x14\n" +
	"\x10KICKED_BY_REVOKE\x10\f\x12\x10\n" +
	"\fFORCE_LOGOUT\x10\r\x12!\n" +
	"\x1dCONVERSATION_DISMISSED_NOTIFY\x10\x0e\x12\x0f\n" +
	"\vCLIENT_AUTH\x101\x12\x10\n" +
	"\fMSG_PUSH_ACK\x102\x12\x14\n" +
	"\x10CLIENT_HEARTBEAT\x103B\x03\x80\x01\x01b\x06proto3"

var (
	file_push_notify_proto_rawDescOnce sync.Once
	file_push_notify_proto_rawDescData []byte
)

func file_push_notify_proto_rawDescGZIP() []byte {
	file_push_notify_proto_rawDescOnce.Do(func() {
		file_push_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_notify_proto_rawDesc), len(file_push_notify_proto_rawDesc)))
	})
	return file_push_notify_proto_rawDescData
}

var file_push_notify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_push_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_push_notify_proto_goTypes = []any{
	(NotifyType)(0),                // 0: chatnow.push.NotifyType
	(*NotifyClientAuth)(nil),       // 1: chatnow.push.NotifyClientAuth
	(*NotifyMsgPushAck)(nil),       // 2: chatnow.push.NotifyMsgPushAck
	(*NotifyHeartbeat)(nil),        // 3: chatnow.push.NotifyHeartbeat
	(*NotifyFriendAddApply)(nil),   // 4: chatnow.push.NotifyFriendAddApply
	(*NotifyFriendAddProcess)(nil), // 5: chatnow.push.NotifyFriendAddProcess
	(*NotifyFriendRemove)(nil),     // 6: chatnow.push.NotifyFriendRemove
	(*NotifyNewConversation)(nil),  // 7: chatnow.push.NotifyNewConversation
	(*NotifyNewMessage)(nil),       // 8: chatnow.push.NotifyNewMessage
	(*NotifyMessageRecalled)(nil),  // 9: chatnow.push.NotifyMessageRecalled
	(*NotifyPresenceChange)(nil),   // 10: chatnow.push.NotifyPresenceChange
	(*NotifyTyping)(nil),           // 11: chatnow.push.NotifyTyping
	(*NotifyReactionChanged)(nil),  // 12: chatnow.push.NotifyReactionChanged
	(*NotifyPinChanged)(nil),       // 13: chatnow.push.NotifyPinChanged
	(*NotifyReadReceipt)(nil),      // 14: chatnow.push.NotifyReadReceipt
	(*NotifyKicked)(nil),           // 15: chatnow.push.NotifyKicked
	(*NotifyMessage)(nil),          // 16: chatnow.push.NotifyMessage
	(*common.UserInfo)(nil),        // 17: chatnow.common.UserInfo
	(*message.Message)(nil),        // 18: chatnow.message.Message
}
var file_push_notify_proto_depIdxs = []int32{
	17, // 0: chatnow.push.NotifyFriendAddApply.user_info:type_name -> chatnow.common.UserInfo
	17, // 1: chatnow.push.NotifyFriendAddProcess.user_info:type_name -> chatnow.common.UserInfo
	18, // 2: chatnow.push.NotifyNewMessage.message_info:type_name -> chatnow.message.Message
	0,  // 3: chatnow.push.NotifyKicked.reason:type_name -> chatnow.push.NotifyType
	0,  // 4: chatnow.push.NotifyMessage.notify_type:type_name -> chatnow.push.NotifyType
	4,  // 5: chatnow.push.NotifyMessage.friend_add_apply:type_name -> chatnow.push.NotifyFriendAddApply
	5,  // 6: chatnow.push.NotifyMessage.friend_process_result:type_name -> chatnow.push.NotifyFriendAddProcess
	6,  // 7: chatnow.push.NotifyMessage.friend_remove:type_name -> chatnow.push.NotifyFriendRemove
	7,  // 8: chatnow.push.NotifyMessage.new_conversation_info:type_name -> chatnow.push.NotifyNewConversation
	8,  // 9: chatnow.push.NotifyMessage.new_message_info:type_name -> chatnow.push.NotifyNewMessage
	2,  // 10: chatnow.push.NotifyMessage.msg_push_ack:type_name -> chatnow.push.NotifyMsgPushAck
	3,  // 11: chatnow.push.NotifyMessage.heartbeat:type_name -> chatnow.push.NotifyHeartbeat
	1,  // 12: chatnow.push.NotifyMessage.client_auth:type_name -> chatnow.push.NotifyClientAuth
	9,  // 13: chatnow.push.NotifyMessage.message_recalled:type_name -> chatnow.push.NotifyMessageRecalled
	10, // 14: chatnow.push.NotifyMessage.presence_change:type_name -> chatnow.push.NotifyPresenceChange
	11, // 15: chatnow.push.NotifyMessage.typing:type_name -> chatnow.push.NotifyTyping
	12, // 16: chatnow.push.NotifyMessage.reaction_changed:type_name -> chatnow.push.NotifyReactionChanged
	13, // 17: chatnow.push.NotifyMessage.pin_changed:type_name -> chatnow.push.NotifyPinChanged
	14, // 18: chatnow.push.NotifyMessage.read_receipt:type_name -> chatnow.push.NotifyReadReceipt
	15, // 19: chatnow.push.NotifyMessage.kicked:type_name -> chatnow.push.NotifyKicked
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_push_notify_proto_init() }
func file_push_notify_proto_init() {
	if File_push_notify_proto != nil {
		return
	}
	file_push_notify_proto_msgTypes[0].OneofWrappers = []any{}
	file_push_notify_proto_msgTypes[15].OneofWrappers = []any{
		(*NotifyMessage_FriendAddApply)(nil),
		(*NotifyMessage_FriendProcessResult)(nil),
		(*NotifyMessage_FriendRemove)(nil),
		(*NotifyMessage_NewConversationInfo)(nil),
		(*NotifyMessage_NewMessageInfo)(nil),
		(*NotifyMessage_MsgPushAck)(nil),
		(*NotifyMessage_Heartbeat)(nil),
		(*NotifyMessage_ClientAuth)(nil),
		(*NotifyMessage_MessageRecalled)(nil),
		(*NotifyMessage_PresenceChange)(nil),
		(*NotifyMessage_Typing)(nil),
		(*NotifyMessage_ReactionChanged)(nil),
		(*NotifyMessage_PinChanged)(nil),
		(*NotifyMessage_ReadReceipt)(nil),
		(*NotifyMessage_Kicked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_notify_proto_rawDesc), len(file_push_notify_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_notify_proto_goTypes,
		DependencyIndexes: file_push_notify_proto_depIdxs,
		EnumInfos:         file_push_notify_proto_enumTypes,
		MessageInfos:      file_push_notify_proto_msgTypes,
	}.Build()
	File_push_notify_proto = out.File
	file_push_notify_proto_goTypes = nil
	file_push_notify_proto_depIdxs = nil
}
