// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: push/push_service.proto

package push

import (
	common "chatnow-tests/proto/chatnow/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushToUserReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Notify          *NotifyMessage         `protobuf:"bytes,3,opt,name=notify,proto3" json:"notify,omitempty"`
	UserSeq         *uint64                `protobuf:"varint,4,opt,name=user_seq,json=userSeq,proto3,oneof" json:"user_seq,omitempty"`
	TargetDeviceIds []string               `protobuf:"bytes,5,rep,name=target_device_ids,json=targetDeviceIds,proto3" json:"target_device_ids,omitempty"` // 空=所有设备；非空=仅指定设备
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PushToUserReq) Reset() {
	*x = PushToUserReq{}
	mi := &file_push_push_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserReq) ProtoMessage() {}

func (x *PushToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserReq.ProtoReflect.Descriptor instead.
func (*PushToUserReq) Descriptor() ([]byte, []int) {
	return file_push_push_service_proto_rawDescGZIP(), []int{0}
}

func (x *PushToUserReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushToUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushToUserReq) GetNotify() *NotifyMessage {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *PushToUserReq) GetUserSeq() uint64 {
	if x != nil && x.UserSeq != nil {
		return *x.UserSeq
	}
	return 0
}

func (x *PushToUserReq) GetTargetDeviceIds() []string {
	if x != nil {
		return x.TargetDeviceIds
	}
	return nil
}

type PushToUserRsp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Header            *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	OnlineDeviceCount int32                  `protobuf:"varint,2,opt,name=online_device_count,json=onlineDeviceCount,proto3" json:"online_device_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PushToUserRsp) Reset() {
	*x = PushToUserRsp{}
	mi := &file_push_push_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserRsp) ProtoMessage() {}

func (x *PushToUserRsp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserRsp.ProtoReflect.Descriptor instead.
func (*PushToUserRsp) Descriptor() ([]byte, []int) {
	return file_push_push_service_proto_rawDescGZIP(), []int{1}
}

func (x *PushToUserRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PushToUserRsp) GetOnlineDeviceCount() int32 {
	if x != nil {
		return x.OnlineDeviceCount
	}
	return 0
}

type PushBatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserIdList    []string               `protobuf:"bytes,2,rep,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	Notify        *NotifyMessage         `protobuf:"bytes,3,opt,name=notify,proto3" json:"notify,omitempty"`
	UserSeqs      []*UserSeqPair         `protobuf:"bytes,4,rep,name=user_seqs,json=userSeqs,proto3" json:"user_seqs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchReq) Reset() {
	*x = PushBatchReq{}
	mi := &file_push_push_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchReq) ProtoMessage() {}

func (x *PushBatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchReq.ProtoReflect.Descriptor instead.
func (*PushBatchReq) Descriptor() ([]byte, []int) {
	return file_push_push_service_proto_rawDescGZIP(), []int{2}
}

func (x *PushBatchReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushBatchReq) GetUserIdList() []string {
	if x != nil {
		return x.UserIdList
	}
	return nil
}

func (x *PushBatchReq) GetNotify() *NotifyMessage {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *PushBatchReq) GetUserSeqs() []*UserSeqPair {
	if x != nil {
		return x.UserSeqs
	}
	return nil
}

type PushBatchRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *common.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	OnlineCount   int32                  `protobuf:"varint,2,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchRsp) Reset() {
	*x = PushBatchRsp{}
	mi := &file_push_push_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchRsp) ProtoMessage() {}

func (x *PushBatchRsp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchRsp.ProtoReflect.Descriptor instead.
func (*PushBatchRsp) Descriptor() ([]byte, []int) {
	return file_push_push_service_proto_rawDescGZIP(), []int{3}
}

func (x *PushBatchRsp) GetHeader() *common.ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PushBatchRsp) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

type UserSeqPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSeq       uint64                 `protobuf:"varint,2,opt,name=user_seq,json=userSeq,proto3" json:"user_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSeqPair) Reset() {
	*x = UserSeqPair{}
	mi := &file_push_push_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSeqPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSeqPair) ProtoMessage() {}

func (x *UserSeqPair) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSeqPair.ProtoReflect.Descriptor instead.
func (*UserSeqPair) Descriptor() ([]byte, []int) {
	return file_push_push_service_proto_rawDescGZIP(), []int{4}
}

func (x *UserSeqPair) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserSeqPair) GetUserSeq() uint64 {
	if x != nil {
		return x.UserSeq
	}
	return 0
}

var File_push_push_service_proto protoreflect.FileDescriptor

const file_push_push_service_proto_rawDesc = "" +
	"\n" +
	"\x17push/push_service.proto\x12\fchatnow.push\x1a\x15common/envelope.proto\x1a\x11push/notify.proto\"\xd5\x01\n" +
	"\rPushToUserReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\x06notify\x18\x03 \x01(\v2\x1b.chatnow.push.NotifyMessageR\x06notify\x12\x1e\n" +
	"\buser_seq\x18\x04 \x01(\x04H\x00R\auserSeq\x88\x01\x01\x12*\n" +
	"\x11target_device_ids\x18\x05 \x03(\tR\x0ftargetDeviceIdsB\v\n" +
	"\t_user_seq\"w\n" +
	"\rPushToUserRsp\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.chatnow.common.ResponseHeaderR\x06header\x12.\n" +
	"\x13online_device_count\x18\x02 \x01(\x05R\x11onlineDeviceCount\"\xbc\x01\n" +
	"\fPushBatchReq\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12 \n" +
	"\fuser_id_list\x18\x02 \x03(\tR\n" +
	"userIdList\x123\n" +
	"\x06notify\x18\x03 \x01(\v2\x1b.chatnow.push.NotifyMessageR\x06notify\x126\n" +
	"\tuser_seqs\x18\x04 \x03(\v2\x19.chatnow.push.UserSeqPairR\buserSeqs\"i\n" +
	"\fPushBatchRsp\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.chatnow.common.ResponseHeaderR\x06header\x12!\n" +
	"\fonline_count\x18\x02 \x01(\x05R\vonlineCount\"A\n" +
	"\vUserSeqPair\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_seq\x18\x02 \x01(\x04R\auserSeq2\x9a\x01\n" +
	"\vPushService\x12F\n" +
	"\n" +
	"PushToUser\x12\x1b.chatnow.push.PushToUserReq\x1a\x1b.chatnow.push.PushToUserRsp\x12C\n" +
	"\tPushBatch\x12\x1a.chatnow.push.PushBatchReq\x1a\x1a.chatnow.push.PushBatchRspB\x03\x80\x01\x01b\x06proto3"

var (
	file_push_push_service_proto_rawDescOnce sync.Once
	file_push_push_service_proto_rawDescData []byte
)

func file_push_push_service_proto_rawDescGZIP() []byte {
	file_push_push_service_proto_rawDescOnce.Do(func() {
		file_push_push_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_push_service_proto_rawDesc), len(file_push_push_service_proto_rawDesc)))
	})
	return file_push_push_service_proto_rawDescData
}

var file_push_push_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_push_push_service_proto_goTypes = []any{
	(*PushToUserReq)(nil),         // 0: chatnow.push.PushToUserReq
	(*PushToUserRsp)(nil),         // 1: chatnow.push.PushToUserRsp
	(*PushBatchReq)(nil),          // 2: chatnow.push.PushBatchReq
	(*PushBatchRsp)(nil),          // 3: chatnow.push.PushBatchRsp
	(*UserSeqPair)(nil),           // 4: chatnow.push.UserSeqPair
	(*NotifyMessage)(nil),         // 5: chatnow.push.NotifyMessage
	(*common.ResponseHeader)(nil), // 6: chatnow.common.ResponseHeader
}
var file_push_push_service_proto_depIdxs = []int32{
	5, // 0: chatnow.push.PushToUserReq.notify:type_name -> chatnow.push.NotifyMessage
	6, // 1: chatnow.push.PushToUserRsp.header:type_name -> chatnow.common.ResponseHeader
	5, // 2: chatnow.push.PushBatchReq.notify:type_name -> chatnow.push.NotifyMessage
	4, // 3: chatnow.push.PushBatchReq.user_seqs:type_name -> chatnow.push.UserSeqPair
	6, // 4: chatnow.push.PushBatchRsp.header:type_name -> chatnow.common.ResponseHeader
	0, // 5: chatnow.push.PushService.PushToUser:input_type -> chatnow.push.PushToUserReq
	2, // 6: chatnow.push.PushService.PushBatch:input_type -> chatnow.push.PushBatchReq
	1, // 7: chatnow.push.PushService.PushToUser:output_type -> chatnow.push.PushToUserRsp
	3, // 8: chatnow.push.PushService.PushBatch:output_type -> chatnow.push.PushBatchRsp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_push_push_service_proto_init() }
func file_push_push_service_proto_init() {
	if File_push_push_service_proto != nil {
		return
	}
	file_push_notify_proto_init()
	file_push_push_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_push_service_proto_rawDesc), len(file_push_push_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_service_proto_goTypes,
		DependencyIndexes: file_push_push_service_proto_depIdxs,
		MessageInfos:      file_push_push_service_proto_msgTypes,
	}.Build()
	File_push_push_service_proto = out.File
	file_push_push_service_proto_goTypes = nil
	file_push_push_service_proto_depIdxs = nil
}
