/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE IF NOT EXISTS `conversation` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `conversation_id` varchar(48) NOT NULL,
  `conversation_name` varchar(64) NULL,
  `conversation_type` tinyint unsigned NOT NULL,
  `create_time` DATETIME(3) NULL,
  `member_count` int unsigned NOT NULL,
  `status` tinyint unsigned NOT NULL,
  `avatar_id` varchar(64) NULL,
  `owner_id` varchar(32) NULL,
  `peer_user_id` varchar(32) NULL,
  `description` varchar(255) NULL,
  `announcement` varchar(1024) NULL,
  `muted_all` tinyint(1) NOT NULL,
  `max_seq` bigint unsigned NOT NULL,
  `update_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `conversation_id_i`
  ON `conversation` (`conversation_id`);

CREATE TABLE IF NOT EXISTS `conversation_member` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `conversation_id` varchar(48) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `last_read_seq` bigint unsigned NOT NULL,
  `last_ack_seq` bigint unsigned NOT NULL,
  `muted` tinyint(1) NOT NULL,
  `visible` tinyint(1) NOT NULL,
  `pin_time` DATETIME(3) NULL,
  `role` tinyint unsigned NOT NULL,
  `alias` varchar(64) NULL,
  `inviter_id` varchar(32) NULL,
  `join_source` tinyint unsigned NOT NULL,
  `join_time` DATETIME(3) NULL,
  `mute_until` DATETIME(3) NULL,
  `is_quit` tinyint(1) NOT NULL,
  `quit_time` DATETIME(3) NULL,
  `draft` text NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_conv_user`
  ON `conversation_member` (
    `conversation_id`,
    `user_id`);

CREATE INDEX `idx_user_conv`
  ON `conversation_member` (
    `user_id`,
    `is_quit`,
    `conversation_id`);

CREATE TABLE IF NOT EXISTS `friend_apply` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` varchar(32) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `peer_id` varchar(32) NOT NULL,
  `status` tinyint unsigned NOT NULL,
  `source` tinyint unsigned NOT NULL,
  `greeting` varchar(255) NULL,
  `remark` varchar(64) NULL,
  `create_time` DATETIME(3) NULL,
  `handle_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `event_id_i`
  ON `friend_apply` (`event_id`);

CREATE INDEX `idx_peer_status_time`
  ON `friend_apply` (
    `peer_id`,
    `status`,
    `create_time`);

CREATE INDEX `idx_user_peer_time`
  ON `friend_apply` (
    `user_id`,
    `peer_id`,
    `create_time`);

CREATE TABLE IF NOT EXISTS `message` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` bigint unsigned NOT NULL,
  `seq_id` bigint unsigned NOT NULL,
  `session_id` varchar(48) NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `message_type` tinyint unsigned NOT NULL,
  `create_time` DATETIME(3) NULL,
  `content` text NULL,
  `client_msg_id` varchar(64) NULL,
  `file_id` varchar(64) NULL,
  `file_name` varchar(255) NULL,
  `file_size` bigint unsigned NULL,
  `reply_to_msg_id` bigint unsigned NULL,
  `status` tinyint unsigned NOT NULL,
  `revoke_time` DATETIME(3) NULL,
  `revoke_by` varchar(32) NULL,
  `edit_time` DATETIME(3) NULL,
  `forward_from_uid` varchar(32) NULL,
  `forward_at` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `message_id_i`
  ON `message` (`message_id`);

CREATE UNIQUE INDEX `uk_session_seq`
  ON `message` (
    `session_id`,
    `seq_id`);

CREATE UNIQUE INDEX `uk_client_msg`
  ON `message` (
    `user_id`,
    `client_msg_id`);

CREATE TABLE IF NOT EXISTS `message_attachment` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` bigint unsigned NOT NULL,
  `order_idx` int NOT NULL,
  `att_type` tinyint unsigned NOT NULL,
  `file_id` varchar(64) NOT NULL,
  `file_name` varchar(255) NULL,
  `file_size` bigint unsigned NOT NULL,
  `mime_type` varchar(64) NULL,
  `thumb_file_id` varchar(64) NULL,
  `width` int unsigned NULL,
  `height` int unsigned NULL,
  `duration_ms` int unsigned NULL,
  `asr_text` text NULL,
  `create_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE INDEX `idx_message`
  ON `message_attachment` (
    `message_id`,
    `order_idx`);

CREATE TABLE IF NOT EXISTS `message_mention` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` bigint unsigned NOT NULL,
  `user_id` varchar(32) NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_msg_user`
  ON `message_mention` (
    `message_id`,
    `user_id`);

CREATE INDEX `idx_user_msg`
  ON `message_mention` (
    `user_id`,
    `message_id`);

CREATE TABLE IF NOT EXISTS `message_pin` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` varchar(48) NOT NULL,
  `message_id` bigint unsigned NOT NULL,
  `pinned_by` varchar(32) NOT NULL,
  `pinned_at` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_conv_msg`
  ON `message_pin` (
    `session_id`,
    `message_id`);

CREATE INDEX `idx_conv`
  ON `message_pin` (`session_id`);

CREATE TABLE IF NOT EXISTS `message_reaction` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` bigint unsigned NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `emoji` varchar(16) NOT NULL,
  `create_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_msg_user_emoji`
  ON `message_reaction` (
    `message_id`,
    `user_id`,
    `emoji`);

CREATE INDEX `idx_msg`
  ON `message_reaction` (`message_id`);

CREATE TABLE IF NOT EXISTS `message_read` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` bigint unsigned NOT NULL,
  `user_id` varchar(32) NOT NULL,
  `read_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_msg_user`
  ON `message_read` (
    `message_id`,
    `user_id`);

CREATE INDEX `idx_msg_time`
  ON `message_read` (
    `message_id`,
    `read_time`);

CREATE TABLE IF NOT EXISTS `relation` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(32) NOT NULL,
  `peer_id` varchar(32) NOT NULL,
  `remark` varchar(64) NULL,
  `group_name` varchar(32) NULL,
  `status` tinyint unsigned NOT NULL,
  `starred` tinyint(1) NOT NULL,
  `create_time` DATETIME(3) NULL,
  `update_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_user_peer`
  ON `relation` (
    `user_id`,
    `peer_id`);

CREATE INDEX `idx_peer_user`
  ON `relation` (
    `peer_id`,
    `user_id`);

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(32) NOT NULL,
  `nickname` varchar(64) NULL,
  `description` varchar(255) NULL,
  `password` varchar(256) NULL,
  `password_salt` varchar(64) NULL,
  `mail` varchar(128) NULL,
  `phone` varchar(20) NULL,
  `avatar_id` varchar(64) NULL,
  `gender` tinyint unsigned NOT NULL,
  `region` varchar(64) NULL,
  `status` tinyint unsigned NOT NULL,
  `register_time` DATETIME(3) NULL,
  `last_login_time` DATETIME(3) NULL,
  `last_login_ip` varchar(45) NULL,
  `update_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `user_id_i`
  ON `user` (`user_id`);

CREATE INDEX `nickname_i`
  ON `user` (`nickname`);

CREATE UNIQUE INDEX `mail_i`
  ON `user` (`mail`);

CREATE UNIQUE INDEX `phone_i`
  ON `user` (`phone`);

CREATE TABLE IF NOT EXISTS `user_block` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `blocker_id` varchar(32) NOT NULL,
  `blocked_id` varchar(32) NOT NULL,
  `create_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `uk_blocker_blocked`
  ON `user_block` (
    `blocker_id`,
    `blocked_id`);

CREATE INDEX `idx_blocked`
  ON `user_block` (`blocked_id`);

CREATE TABLE IF NOT EXISTS `user_device` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(32) NOT NULL,
  `device_id` varchar(128) NOT NULL,
  `device_type` tinyint unsigned NOT NULL,
  `device_name` varchar(64) NULL,
  `app_version` varchar(32) NULL,
  `os_version` varchar(32) NULL,
  `login_session_id` varchar(64) NOT NULL,
  `push_token` varchar(255) NULL,
  `login_ip` varchar(45) NULL,
  `online_status` tinyint unsigned NOT NULL,
  `last_active_time` DATETIME(3) NULL,
  `login_time` DATETIME(3) NULL,
  `expire_time` DATETIME(3) NULL,
  `update_time` DATETIME(3) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `login_session_id_i`
  ON `user_device` (`login_session_id`);

CREATE UNIQUE INDEX `uk_user_device`
  ON `user_device` (
    `user_id`,
    `device_id`);

CREATE UNIQUE INDEX `uk_push_token`
  ON `user_device` (`push_token`);

CREATE TABLE IF NOT EXISTS `user_timeline` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` varchar(32) NOT NULL,
  `user_seq` bigint unsigned NOT NULL,
  `session_id` varchar(48) NOT NULL,
  `session_seq` bigint unsigned NOT NULL,
  `message_id` bigint unsigned NOT NULL,
  `message_time` DATETIME(3) NULL,
  `deliver_status` tinyint unsigned NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `idx_user_seq`
  ON `user_timeline` (
    `user_id`,
    `user_seq`);

CREATE INDEX `idx_user_session_seq`
  ON `user_timeline` (
    `user_id`,
    `session_id`,
    `session_seq`);
