/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE IF NOT EXISTS `media_blob_ref` (
  `content_hash` varchar(72) NOT NULL PRIMARY KEY,
  `bucket` varchar(64) NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `ref_count` int NOT NULL,
  `total_size` bigint NOT NULL,
  `last_decremented_at` DATETIME(3) NULL)
 ENGINE=InnoDB;
CREATE INDEX `idx_refcount_decremented`
  ON `media_blob_ref` (
    `ref_count`,
    `last_decremented_at`);

CREATE TABLE IF NOT EXISTS `media_file` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `file_id` varchar(20) NOT NULL,
  `content_hash` varchar(72) NOT NULL,
  `bucket` varchar(64) NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_size` bigint NOT NULL,
  `mime_type` varchar(128) NOT NULL,
  `purpose` tinyint unsigned NOT NULL,
  `owner_id` varchar(32) NOT NULL,
  `uploaded_at` DATETIME(3) NULL,
  `status` tinyint unsigned NOT NULL,
  `upload_id` varchar(128) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `file_id_i`
  ON `media_file` (`file_id`);

CREATE INDEX `idx_hash`
  ON `media_file` (`content_hash`);

CREATE INDEX `idx_owner_uploaded`
  ON `media_file` (
    `owner_id`,
    `uploaded_at`);

CREATE INDEX `idx_status_uploaded`
  ON `media_file` (
    `status`,
    `uploaded_at`);

CREATE INDEX `idx_upload_id`
  ON `media_file` (`upload_id`);

CREATE TABLE IF NOT EXISTS `media_user_quota` (
  `user_id` varchar(32) NOT NULL PRIMARY KEY,
  `used_bytes` bigint NOT NULL,
  `quota_bytes` bigint NOT NULL,
  `updated_at` DATETIME(3) NULL)
 ENGINE=InnoDB;
